### ISSUE TITLE
chore: update WEBHOOK_URL to real Discord Channel

### ISSUE THREAD

**Issue by alex-pakalniskis** [IndexerDAO/allocation-ages#1]
Currently this repo secret has placeholder text. 

@Web3Slimchance could you:
* create a channel and associated webhook in Discord
* update WEBHOOK_URL secret with the link

Thanks :D

**Comment by alex-pakalniskis** [comment]
Example output (before rendering in Discord): 
![image](https://user-images.githubusercontent.com/43630382/201499884-44c5b89b-1604-4467-9eaa-71c3301de6ff.png)

**Comment by Web3Slimchance** [comment]
Added 👍
